package com.almalence.opencam.ui;

import com.almalence.opencam.CameraParameters;
import com.almalence.opencam.CameraScreenActivity;
import com.almalence.opencam.R;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by marcin on 18.12.2014.
 */
public class AlmalenceGUIInitializer {

    public static final int					FOCUS_AF_LOCK				= 10;

    public static final Map<Integer, Integer> ICONS_SCENE					= new HashMap<Integer, Integer>()
    {
        {
            put(CameraParameters.SCENE_MODE_AUTO,
                    R.drawable.gui_almalence_settings_scene_auto);
            put(CameraParameters.SCENE_MODE_ACTION,
                    R.drawable.gui_almalence_settings_scene_action);
            put(CameraParameters.SCENE_MODE_PORTRAIT,
                    R.drawable.gui_almalence_settings_scene_portrait);
            put(CameraParameters.SCENE_MODE_LANDSCAPE,
                    R.drawable.gui_almalence_settings_scene_landscape);
            put(CameraParameters.SCENE_MODE_NIGHT,
                    R.drawable.gui_almalence_settings_scene_night);
            put(CameraParameters.SCENE_MODE_NIGHT_PORTRAIT,
                    R.drawable.gui_almalence_settings_scene_nightportrait);
            put(CameraParameters.SCENE_MODE_THEATRE,
                    R.drawable.gui_almalence_settings_scene_theater);
            put(CameraParameters.SCENE_MODE_BEACH,
                    R.drawable.gui_almalence_settings_scene_beach);
            put(CameraParameters.SCENE_MODE_SNOW,
                    R.drawable.gui_almalence_settings_scene_snow);
            put(CameraParameters.SCENE_MODE_SUNSET,
                    R.drawable.gui_almalence_settings_scene_sunset);
            put(CameraParameters.SCENE_MODE_STEADYPHOTO,
                    R.drawable.gui_almalence_settings_scene_steadyphoto);
            put(CameraParameters.SCENE_MODE_FIREWORKS,
                    R.drawable.gui_almalence_settings_scene_fireworks);
            put(CameraParameters.SCENE_MODE_SPORTS,
                    R.drawable.gui_almalence_settings_scene_sports);
            put(CameraParameters.SCENE_MODE_PARTY,
                    R.drawable.gui_almalence_settings_scene_party);
            put(CameraParameters.SCENE_MODE_CANDLELIGHT,
                    R.drawable.gui_almalence_settings_scene_candlelight);
            put(CameraParameters.SCENE_MODE_BARCODE,
                    R.drawable.gui_almalence_settings_scene_barcode);
        }
    };


    public static final Map<Integer, Integer>	ICONS_WB					= new HashMap<Integer, Integer>()
    {
        {
            put(CameraParameters.WB_MODE_AUTO,
                    R.drawable.gui_almalence_settings_wb_auto);
            put(CameraParameters.WB_MODE_INCANDESCENT,
                    R.drawable.gui_almalence_settings_wb_incandescent);
            put(CameraParameters.WB_MODE_FLUORESCENT,
                    R.drawable.gui_almalence_settings_wb_fluorescent);
            put(CameraParameters.WB_MODE_WARM_FLUORESCENT,
                    R.drawable.gui_almalence_settings_wb_warmfluorescent);
            put(CameraParameters.WB_MODE_DAYLIGHT,
                    R.drawable.gui_almalence_settings_wb_daylight);
            put(CameraParameters.WB_MODE_CLOUDY_DAYLIGHT,
                    R.drawable.gui_almalence_settings_wb_cloudydaylight);
            put(CameraParameters.WB_MODE_TWILIGHT,
                    R.drawable.gui_almalence_settings_wb_twilight);
            put(CameraParameters.WB_MODE_SHADE,
                    R.drawable.gui_almalence_settings_wb_shade);
        }
    };

    public static final Map<Integer, Integer>	ICONS_FOCUS					= new HashMap<Integer, Integer>()
    {
        {
            put(CameraParameters.AF_MODE_AUTO,
                    R.drawable.gui_almalence_settings_focus_auto);
            put(CameraParameters.AF_MODE_INFINITY,
                    R.drawable.gui_almalence_settings_focus_infinity);
            put(CameraParameters.AF_MODE_NORMAL,
                    R.drawable.gui_almalence_settings_focus_normal);
            put(CameraParameters.AF_MODE_MACRO,
                    R.drawable.gui_almalence_settings_focus_macro);
            put(CameraParameters.AF_MODE_FIXED,
                    R.drawable.gui_almalence_settings_focus_fixed);
            put(CameraParameters.AF_MODE_EDOF,
                    R.drawable.gui_almalence_settings_focus_edof);
            put(CameraParameters.AF_MODE_CONTINUOUS_VIDEO,
                    R.drawable.gui_almalence_settings_focus_continiuousvideo);
            put(CameraParameters.AF_MODE_CONTINUOUS_PICTURE,
                    R.drawable.gui_almalence_settings_focus_continiuouspicture);
            put(FOCUS_AF_LOCK,
                    R.drawable.gui_almalence_settings_focus_aflock);
        }
    };

    public static final Map<Integer, Integer>	ICONS_FLASH					= new HashMap<Integer, Integer>()
    {
        {
            put(CameraParameters.FLASH_MODE_OFF,
                    R.drawable.gui_almalence_settings_flash_off);
            put(CameraParameters.FLASH_MODE_AUTO,
                    R.drawable.gui_almalence_settings_flash_auto);
            put(CameraParameters.FLASH_MODE_SINGLE,
                    R.drawable.gui_almalence_settings_flash_on);
            put(CameraParameters.FLASH_MODE_REDEYE,
                    R.drawable.gui_almalence_settings_flash_redeye);
            put(CameraParameters.FLASH_MODE_TORCH,
                    R.drawable.gui_almalence_settings_flash_torch);
        }
    };

    public static final Map<Integer, Integer>	ICONS_ISO					= new HashMap<Integer, Integer>()
    {
        {
            put(CameraParameters.ISO_AUTO,
                    R.drawable.gui_almalence_settings_iso_auto);
            put(CameraParameters.ISO_50,
                    R.drawable.gui_almalence_settings_iso_50);
            put(CameraParameters.ISO_100,
                    R.drawable.gui_almalence_settings_iso_100);
            put(CameraParameters.ISO_200,
                    R.drawable.gui_almalence_settings_iso_200);
            put(CameraParameters.ISO_400,
                    R.drawable.gui_almalence_settings_iso_400);
            put(CameraParameters.ISO_800,
                    R.drawable.gui_almalence_settings_iso_800);
            put(CameraParameters.ISO_1600,
                    R.drawable.gui_almalence_settings_iso_1600);
            put(CameraParameters.ISO_3200,
                    R.drawable.gui_almalence_settings_iso_3200);
        }
    };

    public static final Map<String, Integer>	ICONS_DEFAULT_ISO			= new HashMap<String, Integer>()
    {
        {
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.isoAutoDefaultSystem),
                    R.drawable.gui_almalence_settings_iso_auto);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso50DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_50);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso100DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_100);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso200DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_200);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso400DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_400);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso800DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_800);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso1600DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_1600);
            put(CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso3200DefaultSystem),
                    R.drawable.gui_almalence_settings_iso_3200);
        }
    };

    public static final Map<Integer, Integer>	ICONS_METERING				= new HashMap<Integer, Integer>()
    {
        {
            put(0,
                    R.drawable.gui_almalence_settings_metering_auto);
            put(1,
                    R.drawable.gui_almalence_settings_metering_matrix);
            put(2,
                    R.drawable.gui_almalence_settings_metering_center);
            put(3,
                    R.drawable.gui_almalence_settings_metering_spot);
        }
    };

    // List of localized names for camera parameters values
    public static final Map<Integer, String>	NAMES_SCENE					= new HashMap<Integer, String>()
    {
        {
            put(CameraParameters.SCENE_MODE_AUTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneAuto));
            put(CameraParameters.SCENE_MODE_ACTION,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneAction));
            put(CameraParameters.SCENE_MODE_PORTRAIT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.scenePortrait));
            put(CameraParameters.SCENE_MODE_LANDSCAPE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneLandscape));
            put(CameraParameters.SCENE_MODE_NIGHT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneNight));
            put(CameraParameters.SCENE_MODE_NIGHT_PORTRAIT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneNightPortrait));
            put(CameraParameters.SCENE_MODE_THEATRE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneTheatre));
            put(CameraParameters.SCENE_MODE_BEACH,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneBeach));
            put(CameraParameters.SCENE_MODE_SNOW,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneSnow));
            put(CameraParameters.SCENE_MODE_SUNSET,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneSunset));
            put(CameraParameters.SCENE_MODE_STEADYPHOTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneSteadyPhoto));
            put(CameraParameters.SCENE_MODE_FIREWORKS,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneFireworks));
            put(CameraParameters.SCENE_MODE_SPORTS,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneSports));
            put(CameraParameters.SCENE_MODE_PARTY,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneParty));
            put(CameraParameters.SCENE_MODE_CANDLELIGHT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneCandlelight));
            put(CameraParameters.SCENE_MODE_BARCODE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.sceneBarcode));
        }
    };

    public static final Map<Integer, String>	NAMES_WB					= new HashMap<Integer, String>()
    {
        {
            put(CameraParameters.WB_MODE_AUTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbAuto));
            put(CameraParameters.WB_MODE_INCANDESCENT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbIncandescent));
            put(CameraParameters.WB_MODE_FLUORESCENT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbFluorescent));
            put(CameraParameters.WB_MODE_WARM_FLUORESCENT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbWarmFluorescent));
            put(CameraParameters.WB_MODE_DAYLIGHT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbDaylight));
            put(CameraParameters.WB_MODE_CLOUDY_DAYLIGHT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbCloudyDaylight));
            put(CameraParameters.WB_MODE_TWILIGHT,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbTwilight));
            put(CameraParameters.WB_MODE_SHADE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.wbShade));
        }
    };

    public static final Map<Integer, String>	NAMES_FOCUS					= new HashMap<Integer, String>()
    {
        {
            put(CameraParameters.AF_MODE_AUTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusAuto));
            put(CameraParameters.AF_MODE_INFINITY,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusInfinity));
            put(CameraParameters.AF_MODE_NORMAL,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusNormal));
            put(CameraParameters.AF_MODE_MACRO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusMacro));
            put(CameraParameters.AF_MODE_FIXED,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusFixed));
            put(CameraParameters.AF_MODE_EDOF,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusEdof));
            put(CameraParameters.AF_MODE_CONTINUOUS_VIDEO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusContinuousVideo));
            put(CameraParameters.AF_MODE_CONTINUOUS_PICTURE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.focusContinuousPicture));
        }
    };

    public static final Map<Integer, String>	NAMES_FLASH					= new HashMap<Integer, String>()
    {
        {
            put(CameraParameters.FLASH_MODE_OFF,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.flashOff));
            put(CameraParameters.FLASH_MODE_AUTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.flashAuto));
            put(CameraParameters.FLASH_MODE_SINGLE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.flashOn));
            put(CameraParameters.FLASH_MODE_REDEYE,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.flashRedEye));
            put(CameraParameters.FLASH_MODE_TORCH,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.flashTorch));
        }
    };

    public static final Map<Integer, String>	NAMES_ISO					= new HashMap<Integer, String>()
    {
        {
            put(CameraParameters.ISO_AUTO,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.isoAuto));
            put(CameraParameters.ISO_50,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso50));
            put(CameraParameters.ISO_100,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso100));
            put(CameraParameters.ISO_200,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso200));
            put(CameraParameters.ISO_400,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso400));
            put(CameraParameters.ISO_800,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso800));
            put(CameraParameters.ISO_1600,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso1600));
            put(CameraParameters.ISO_3200,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.iso3200));
        }
    };

    public static final Map<Integer, String>	NAMES_METERING				= new HashMap<Integer, String>()
    {
        {
            put(0,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.meteringAutoSystem));
            put(1,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.meteringMatrixSystem));
            put(2,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.meteringCenterSystem));
            put(3,
                    CameraScreenActivity
                            .getInstance()
                            .getResources()
                            .getString(
                                    R.string.meteringSpotSystem));
        }
    };

    public static final Map<String, String>	UNLOCK_MODE_PREFERENCES		= new HashMap<String, String>()
    {
        {
            put("hdrmode",
                    "plugin_almalence_hdr");
            put("movingobjects",
                    "plugin_almalence_moving_burst");
            put("sequence",
                    "plugin_almalence_hdr");
            put("groupshot",
                    "plugin_almalence_groupshot");
            put("panorama_augmented",
                    "plugin_almalence_panorama");
        }
    };
}
